// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CheckUpdate():Promise<types.Tag>;

export function Start(arg1:context.Context):Promise<void>;
