// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['system']['Update']['CheckUpdate']();
}

export function Start(arg1) {
  return window['go']['system']['Update']['Start'](arg1);
}
