// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName() {
  return window['go']['config']['AppConfig']['GetAppName']();
}

export function GetConfig() {
  return window['go']['config']['AppConfig']['GetConfig']();
}

export function GetVersion() {
  return window['go']['config']['AppConfig']['GetVersion']();
}

export function SaveConfig(arg1) {
  return window['go']['config']['AppConfig']['SaveConfig'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['config']['AppConfig']['SaveTheme'](arg1);
}

export function Start(arg1) {
  return window['go']['config']['AppConfig']['Start'](arg1);
}
