// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function GetAppName():Promise<string>;

export function GetConfig():Promise<types.Config>;

export function GetVersion():Promise<string>;

export function SaveConfig(arg1:types.Config):Promise<string>;

export function SaveTheme(arg1:string):Promise<string>;

export function Start(arg1:context.Context):Promise<void>;
