name: Python application windows

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - windows/amd64
    # 步骤合集
    steps:
    - uses: actions/checkout@v3
    - name: Normalise platform tag
      id: normalise_platform
      shell: bash
      run: |
        tag=$(echo ${{ matrix.platform }} | sed -e 's/\//_/g')
        echo "tag=$tag" >> "$GITHUB_OUTPUT"

    - name: Normalise version tag
      id: normalise_version
      shell: bash
      run: |
        version=$(echo ${{ github.event.release.tag_name }} | sed -e 's/v//g')
        echo "version=$version" >> "$GITHUB_OUTPUT"
          
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        flet pack main.py -i assets/icon.ico  -n kafka-king

    - name: Upload release asset
      shell: bash
      working-directory: ./dist
      run: |
        filepath="kafka-king.exe"
        filename="kafka-king_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}.exe"
        upload_url="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${{ github.event.release.id }}/assets"
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @$filepath "$upload_url?name=$filename"
